### ISSUE TITLE
[feature] Can we make Ctrl+Shift+v to paste in terminal?

### ISSUE THREAD

**Issue by santosh** [kentonv/dvorak-qwerty#9]
OS: CentOS Linux release 7.6.1810 (Core) 
$XDG_SESSION_TYPE: x11
$DESKTOP_SESSION: mate

Sometimes while skimming through documentation online, I usually just copy and paste it into my vim session running inside my terminal. The `xdq` tool works fine with normal C-c, C-v, C-x, but should it also handle C-S-v?

**Comment by kentonv** [comment]
Hi Santosh,

Hmm, it looks to me like ctrl+shift is in fact among the list of modifier combinations that xdq grabs:

https://github.com/kentonv/dvorak-qwerty/blob/41f27db9e17ffb5081be85450a197d049c350b3d/unix/xdq.c#L212-L219

I use ctrl+shift+v a lot for "paste text-only" in Chrome so I think I would have noticed if it didn't work -- however, I haven't used xdq in some time now as I now prefer the systemtap approach. So I could be mis-remembering.

If it indeed doesn't work then I'm afraid I don't really know why. Unfortunately xdq has a lot of obscure problems, sometimes applying only to specific apps.

Happy to accept a PR if you figure it out, though.

**Comment by santosh** [comment]
Well, it works on my home computer. Below is the config:

OS: Fedora Workstation 30
$XDG_SESSION_TYPE: x11
$DESKTOP_SESSION: /usr/share/xsessions/plasma

Closing this issue as of now.

**Comment by kentonv** [comment]
Weird.

Is it possible that the computer where it didn't work is running Wayland instead of X? xdq doesn't really work on Wayland (it seems to work in some apps but not others) due to Wayland enforcing a stronger security model preventing apps from interfering with each other's input. Wayland is increasingly common in newer Linux distributions (and depending on whether the machine's video hardware is supported).

**Comment by santosh** [comment]
Anyway, I found a new layout called Colemak. :grinning:
